plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"

yarnPath: .yarn/releases/yarn-2.4.0.cjs

packageExtensions:
  react-scripts@*:
    dependencies:
      sass: "^1.32.7"
      eslint-config-react-app: "^6.0.0"
  office-ui-fabric-react@*:
    peerDependencies:
      react: "*"
  "@uifabric/styling@*":
    peerDependencies:
      react: "*"
  "@uifabric/react-hooks@*":
    peerDependencies:
      react: "*"
  "@uifabric/foundation@*":
    peerDependencies:
      react: "*"
  "@fluentui/theme@*":
    peerDependencies:
      react: "*"
  "@fluentui/react-focus@*":
    peerDependencies:
      react: "*"
  "@uifabric/icons@*":
    peerDependencies:
      react: "*"
