enableInlineHunks: true

packageExtensions:
  "@fluentui/react-focus@*":
    peerDependencies:
      react: "*"
  "@fluentui/theme@*":
    peerDependencies:
      react: "*"
  "@uifabric/foundation@*":
    peerDependencies:
      react: "*"
  "@uifabric/icons@*":
    peerDependencies:
      react: "*"
  "@uifabric/react-hooks@*":
    peerDependencies:
      react: "*"
  "@uifabric/styling@*":
    peerDependencies:
      react: "*"
  office-ui-fabric-react@*:
    peerDependencies:
      react: "*"
  react-scripts@*:
    dependencies:
      eslint-config-react-app: ^6.0.0
      sass: ^1.32.7

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"

yarnPath: .yarn/releases/yarn-2.4.2.cjs
